void Print_keywords()
{
    printf("\n Ver video 10a \n");
    printf("\n auto: No tiene utilidad hoy en dia, solo sirve para que codigo viejo siga funcionando \n");
    printf("\n break \n ");
    printf("\n case \n");
    printf("\n const \n");
    printf("\n continue: es parecido al break pero vuelve al lugar de control \n");
    printf("\n default \n");
    printf("\n do\n");
    printf("\n double\n");
    printf("\n else\n");
    printf("\n enum: Parecido a una estructura, se definen constantes enteras \n");
    printf("\n extern: metodo para no definir una variable, sino para declararla \n");
    printf("\n float\n");
    printf("\n for");
    printf("\n goto: Peor que el covid\n");
    printf("\n if\n");
    printf("\n inline: valia la pena, ahora no. Ayuda a optimizar \n");
    printf("\n int\n");
    printf("\n long\n");
    printf("\n register: variable de tipo registro, el compilador se encarga de hacerlo mejor (no toquees) \n");
    printf("\n restrict: se aplica a variable de tipo puntero, sirve para hacer optimizaciones\n");
    printf("\n return\n");
    printf("\n short\n");
    printf("\n signed: depende de la implementacion, muy poco util\n");
    printf("\n sizeof: es un operador\n");
    printf("\n static: para que una variable que es automatica, pase a ser estatica, sirve para multiples fuentes\n");
    printf("\n struct\n");
    printf("\n switch\n");
    printf("\n typedef: alias de tipos de datos, como en haskell\n");
    printf("\n union\n");
    printf("\n unsigned\n");
    printf("\n void\n");
    printf("\n volatile: bajo nivel\n");
    printf("\n while\n");
    printf("\n \n No vamos a utilizar \n\n");
    printf("\n _Alignas: alinear variables segun otro tipo de datos\n");
    printf("\n _Alignof\n");
    printf("\n _Generic: sobrecarga de nombres para preprocesador\n");
    printf("\n _Atomic: multi hilos\n");
    printf("\n _Noreturn: como llamar a la funcion abort\n");
    printf("\n _Static_assert\n");
    printf("\n _Thread_local:\n");
    printf("\n \n -------------------\n\n");
    printf("\n _Bool: c originalmente no lo tenia\n");
    printf("\n _Complex\n");
    printf("\n _Imaginary\n");

    printf("\n \n");
}